{"version":"3.10.1","messages":["\nAn error occurred while loading ./spec/models/recipe_spec.rb.\n\u001b[31mFailure/Error:\u001b[0m\n\u001b[31m  RSpec.describe Recipe, type: :model do\u001b[0m\n\u001b[31m    it \"can be created with valid data\" do\u001b[0m\n\u001b[31m      user = User.create(username: \"test_user\", password: \"sup3r-secret\", image_url: \"https://via.placeholder.com/150\", bio: \"bio\")\u001b[0m\n\u001b[31m      recipe = Recipe.new(\u001b[0m\n\u001b[31m        user_id: user.id,\u001b[0m\n\u001b[31m        title: \"Rice\", \u001b[0m\n\u001b[31m        instructions: \"Measure 1 cup of rice in bowl of rice cooker. Wash rice. Fill with water to level indicated by manufacturer. Put bowl in rice cooker. Press 'Cook'. Enjoy!\",\u001b[0m\n\u001b[31m        minutes_to_complete: 10\u001b[0m\n\u001b[31m      )\u001b[0m\n\u001b[31m      expect(recipe).to be_valid\u001b[0m\n\u001b[31m\u001b[0m\n\u001b[31mNameError:\u001b[0m\n\u001b[31m  uninitialized constant Recipe\u001b[0m\n\u001b[36m# ./spec/models/recipe_spec.rb:3:in `\u003ctop (required)\u003e'\u001b[0m\n","\nAn error occurred while loading ./spec/models/user_spec.rb.\n\u001b[31mFailure/Error:\u001b[0m\n\u001b[31m  RSpec.describe User, type: :model do\u001b[0m\n\u001b[31m    it \"can be created successfully with valid data\" do\u001b[0m\n\u001b[31m      user = User.create(username: \"test_user\", password: \"sup3r-secret\", image_url: \"https://via.placeholder.com/150\", bio: \"bio\")\u001b[0m\n\u001b[31m      expect(user).to be_valid\u001b[0m\n\u001b[31m    end\u001b[0m\n\u001b[31m  \u001b[0m\n\u001b[31m    it \"has many recipes\" do\u001b[0m\n\u001b[31m      expect(User.new).to respond_to(:recipes)\u001b[0m\n\u001b[31m    end\u001b[0m\n\u001b[31m  \u001b[0m\n\u001b[31m\u001b[0m\n\u001b[31mNameError:\u001b[0m\n\u001b[31m  uninitialized constant User\u001b[0m\n\u001b[36m# ./spec/models/user_spec.rb:3:in `\u003ctop (required)\u003e'\u001b[0m\n"],"examples":[],"summary":{"duration":5.12e-05,"example_count":0,"failure_count":0,"pending_count":0,"errors_outside_of_examples_count":2},"summary_line":"0 examples, 0 failures, 2 errors occurred outside of examples"}